In [ ]:
# Présentation du Jeu de la Vie
## **Projet Python : Simulation et Analyse du Jeu de la Vie**

### Objectifs :
- Presenter les concepts cles du Jeu de la Vie.
- Demontrer les fonctionnalites du projet avec des exemples pratiques.
- Mettre en avant les analyses et les resultats obtenus.


In [ ]:
## **1. Description Générale**

Le Jeu de la Vie, cree par John Conway en 1970, est un automate cellulaire simulant des dynamiques complexes à partir de regles simples.

### **Règles du Jeu :**
1. Une cellule **vivante** survit si elle a 2 ou 3 voisins vivants.
2. Une cellule **vivante** meurt si elle a trop ou trop peu de voisins.
3. Une cellule **morte** devient vivante si elle a exactement 3 voisins vivants.

### Types de structures observées :
- **Structures fixes** : restent immobiles.
- **Oscillateurs** : evoluent de façon cyclique.
- **Vaisseaux** : se deplacent sur la grille.
- **Generateurs** : produisent d autres structures.


In [ ]:
## **2. Partie Moteur de Jeu**

### Objectifs :
- Concevoir un moteur permettant de simuler le jeu en respectant les regles.
- Gerer une grille de cellules pouvant evoluer au fil du temps.


In [1]:
import numpy as np

# Définition de la grille
def initialiser_grille(taille, aleatoire=True):
    if aleatoire:
        return np.random.randint(2, size=(taille, taille))
    return np.zeros((taille, taille), dtype=int)

# Fonction d'évolution de la grille
def appliquer_regles(grille):
    taille = grille.shape[0]
    nouvelle_grille = np.zeros_like(grille)
    for x in range(taille):
        for y in range(taille):
            # Calcul des voisins vivants
            voisins_vivants = np.sum(grille[max(0, x-1):x+2, max(0, y-1):y+2]) - grille[x, y]
            # Application des règles
            if grille[x, y] == 1 and 2 <= voisins_vivants <= 3:
                nouvelle_grille[x, y] = 1
            elif grille[x, y] == 0 and voisins_vivants == 3:
                nouvelle_grille[x, y] = 1
    return nouvelle_grille

# Initialisation et premier pas
grille = initialiser_grille(10)
print("Grille initiale:")
print(grille)

nouvelle_grille = appliquer_regles(grille)
print("Grille après 1 itération:")
print(nouvelle_grille)


Grille initiale:
[[0 0 0 1 0 0 1 1 0 1]
 [1 1 1 1 0 0 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 1]
 [1 0 0 1 0 1 1 0 0 0]
 [1 0 1 0 0 1 1 1 0 1]
 [1 0 0 0 0 1 1 0 1 0]
 [0 1 1 1 0 1 0 0 1 1]
 [0 1 1 0 1 0 1 1 0 0]
 [1 0 0 1 0 1 0 0 0 1]
 [1 1 1 1 1 0 0 1 1 0]]
Grille après 1 itération:
[[0 1 0 1 0 0 1 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 1 1]
 [1 0 0 0 0 0 1 1 0 1]
 [1 0 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 0 0 0 1 0]]


In [14]:
## **3. Partie Interface**

### Objectifs :
- Afficher la grille en temps reel.
- Permettre à l utilisateur de modifier les cellules avec la souris.


SyntaxError: invalid syntax (248306357.py, line 4)

In [3]:
import pygame

# Initialiser Pygame
def afficher_interface(grille):
    pygame.init()
    taille_cellule = 10
    taille_grille = len(grille) * taille_cellule
    screen = pygame.display.set_mode((taille_grille, taille_grille))
    pygame.display.set_caption("Jeu de la Vie")
    clock = pygame.time.Clock()
    running = True

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # Dessiner la grille
        screen.fill((0, 0, 0))
        for x in range(len(grille)):
            for y in range(len(grille)):
                couleur = (200, 200, 200) if grille[x, y] == 1 else (50, 50, 50)
                pygame.draw.rect(screen, couleur,
                                 (x*taille_cellule, y*taille_cellule, taille_cellule, taille_cellule))
        pygame.display.flip()
        clock.tick(10)

    pygame.quit()

# Affichage d'une grille initiale
grille = initialiser_grille(50)
afficher_interface(grille)


pygame 2.6.1 (SDL 2.28.4, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


KeyboardInterrupt: 

In [ ]:
## **4. Sauvegarde et Chargement**

### Objectifs :
- Enregistrer et recharger des etats de grille.


In [1]:
import json
import numpy as np
import pygame

# source d'aide pour json : https://zestedesavoir.com/tutoriels/2514/un-zeste-de-python/6-entrees-sorties/10-tp/

pygame 2.6.1 (SDL 2.28.4, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# Fonction pour sauvegarder l'état du jeu
def save_jeu(fichier, grille, regles):
    try:
        game_state = {
            "taille_grille": grille.shape[0],
            "regles": regles,
            "grille": grille.tolist(),
        }

        with open(fichier, 'w') as file:
            json.dump(game_state, file)

        print(f"Jeu sauvegardé à : {fichier}")
    except Exception as e:
        print(f"Erreur: {e}")


In [5]:
# Fonction pour charger l'état du jeu
def load_jeu(fichier):
    try:
        with open(fichier, 'r') as file:
            game_state = json.load(file)
            print("Jeu load:", game_state)  # Debugging line

        taille_grille = game_state["taille_grille"]
        regles = game_state["regles"]
        grille = np.array(game_state["grille"], dtype=int)

        print(f"Jeu load from {fichier}")
        return grille, regles
    except Exception as e:
        print(f"Erreur: {e}")
        return None


In [6]:
# Fonction pour demander le nom d'un fichier via une interface Pygame
# besoin de Pygame
def demander_nom_fichier(screen):
    input_box = pygame.Rect(300, 350, 400, 50)
    font = pygame.font.Font(None, 36)
    actif = True
    texte = ""
    running = True

    while running:
        screen.fill((240, 248, 255))  # Fond blanc cassé

        # Affiche la boîte de texte
        pygame.draw.rect(screen, (200, 200, 200), input_box)
        pygame.draw.rect(screen, (0, 0, 0), input_box, 2)
        text_surface = font.render(texte, True, (0, 0, 0))
        screen.blit(text_surface, (input_box.x + 5, input_box.y + 10))

        # Affiche un texte explicatif
        message = font.render("Entrez le nom du fichier et appuyez sur Entrée", True, (0, 0, 0))
        screen.blit(message, (200, 250))

        pygame.display.flip()

        # Clavier
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                return None
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_RETURN:
                    return texte
                elif event.key == pygame.K_BACKSPACE:
                    texte = texte[:-1]
                else:
                    texte += event.unicode

    return texte


In [9]:
# Exemple d'utilisation des fonctions save_game et load_game
# Exécutez cette cellule pour tester la sauvegarde et le chargement d'une grille fictive.

# Exemple de grille et règles
grille_exemple = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
regles_exemple = {"survie": [2, 3], "naissance": [3]}

# Sauvegarder la grille
print("=== Sauvegarde ===")
save_jeu("grille_sauvegardee.json", grille_exemple, regles_exemple)

# Charger la grille
print("\n=== Chargement ===")
grille_chargee, regles_chargees = load_jeu("grille_sauvegardee.json")
print("Grille chargée :\n", grille_chargee)
print("Règles chargées :", regles_chargees)


=== Sauvegarde ===
Jeu saved à grille_sauvegardee.json

=== Chargement ===
Jeu loaded: {'taille_grille': 3, 'regles': {'survie': [2, 3], 'naissance': [3]}, 'grille': [[0, 1, 0], [1, 0, 1], [0, 1, 0]]}
Jeu loaded de fichier grille_sauvegardee.json
Grille chargée :
 [[0 1 0]
 [1 0 1]
 [0 1 0]]
Règles chargées : {'survie': [2, 3], 'naissance': [3]}


In [ ]:
## **5. Optimisation et Analyse**

### Objectifs :
- Etudier les performances sur des grilles de grandes tailles.
- Analyser l évolution des cellules.


In [ ]:
import numpy as np
import time

# Fonction d'optimisation pour le calcul des états des cellules
def appliquer_regles_optimise(grille, regles):
    vivantes = np.argwhere(grille == 1)  # Trouver les cellules vivantes
    a_verifier = set()  # Ensemble des cellules à vérifier

    # Ajouter les cellules vivantes et leurs voisins à vérifier
    for x, y in vivantes:
        a_verifier.add((x, y))
        for dx, dy in [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]:
            a_verifier.add(((x + dx) % grille.shape[0], (y + dy) % grille.shape[1]))

    nouvelle_grille = grille.copy()

    # Appliquer les règles sur les cellules à vérifier
    for x, y in a_verifier:
        voisins_vivants = np.sum(grille[x-1:x+2, y-1:y+2]) - grille[x, y]  # Compte les voisins vivants
        if grille[x, y] == 1:
            if voisins_vivants < regles['min_vivants'] or voisins_vivants > regles['max_vivants']:
                nouvelle_grille[x, y] = 0  # La cellule meurt
        else:
            if voisins_vivants == regles['revient_a_la_vie']:
                nouvelle_grille[x, y] = 1  # La cellule revient à la vie

    return nouvelle_grille

# Mesure du temps d'exécution de l'application des règles
def mesurer_temps_execution(grille, regles):
    debut = time.time()  # Heure de début
    nouvelle_grille = appliquer_regles_optimise(grille, regles)  # Application des règles
    fin = time.time()  # Heure de fin
    duree = fin - debut  # Calcul de la durée
    return duree, nouvelle_grille


In [ ]:
def afficher_popup(fenetre, temps):
    # Dimensions de la fenêtre pop-up
    largeur, hauteur = 250, 50

    # Positionnement de la pop-up en bas à droite
    x = 750
    y = 500

    # Fond de la pop-up
    pygame.draw.rect(fenetre, (0, 0, 0), (x, y, largeur, hauteur))
    pygame.draw.rect(fenetre, (255, 255, 255), (x + 5, y + 5, largeur - 10, hauteur - 10))

    # Texte de la pop-up
    font_popup = pygame.font.Font(None, 26)
    texte = font_popup.render(f"Temps: {temps:.6f} secondes", True, (0, 0, 0))
    texte_rect = texte.get_rect(center=(x + largeur // 2, y + hauteur // 2))
    fenetre.blit(texte, texte_rect)

    pygame.display.flip()

    # Délai pour fermer la pop-up après 2 secondes
    pygame.time.delay(500)


In [ ]:
# Fonction principale du jeu
def boucle_jeu_optimisé(taille_grille, regles):
    taille_cellule = 800 // taille_grille
    grille = np.zeros((taille_grille, taille_grille), dtype=int)
    running = True
    auto_mode = False
    clock = pygame.time.Clock()

    while running:
        screen.fill(fonctions_base.COULEUR_FOND)
        fonctions_base.dessiner_grille(screen, grille, taille_cellule)

        # Afficher boutons de contrôle
        boutons = []
        bouton_random = pygame.Rect(850, 60, 140, 50)
        bouton_reset = pygame.Rect(850, 120, 140, 50)
        bouton_step = pygame.Rect(850, 180, 140, 50)
        bouton_auto = pygame.Rect(850, 240, 140, 50)
        bouton_quitter = pygame.Rect(850, 300, 140, 50)
        bouton_save = pygame.Rect(850, 360, 140, 50)

        boutons.extend([("reset", bouton_reset), ("step", bouton_step), ("auto", bouton_auto), ("random", bouton_random), ("quitter", bouton_quitter), ("save", bouton_save)])

        for nom, bouton in boutons:
            texte = "Auto: ON" if auto_mode and nom == "auto" else nom.capitalize()
            fonctions_base.dessiner_bouton(screen, bouton, texte, bouton.collidepoint(pygame.mouse.get_pos()))

        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:  # Clic gauche
                    for nom, bouton in boutons:
                        if bouton.collidepoint(event.pos):
                            if nom == "reset":
                                grille = np.zeros((taille_grille, taille_grille), dtype=int)
                            elif nom == "step":
                                grille = appliquer_regles_optimise(grille, regles)
                                duree, grille = mesurer_temps_execution(grille, regles)
                                afficher_popup(screen, duree)
                                print(f"Temps pour cette étape : {duree:.6f} secondes")
                            elif nom == "auto":
                                auto_mode = not auto_mode
                            elif nom == "save":
                                nom_fichier = save.demander_nom_fichier(screen)
                                if nom_fichier:
                                    save.save_game(nom_fichier + ".json", grille, regles)
                            elif nom == "random":
                                grille = np.random.randint(2, size=(taille_grille, taille_grille))
                            elif nom == "quitter":
                                return fonctions_base.afficher_accueil()
                x, y = event.pos
                if x < 800 and y < 800:  # Clic dans la grille
                    x //= taille_cellule
                    y //= taille_cellule
                    grille[x, y] = 1 - grille[x, y]

        if auto_mode:
            grille = appliquer_regles_optimise(grille, regles)
            pygame.time.delay(300)

        clock.tick(60)

In [ ]:
## **6. Conclusion**

### Points clés du projet :
- Implementation reussie des fonctionnalites principales.
- Interface graphique fonctionnelle avec Pygame.
- Outils d analyse et d optimisation pour etudier le comportement des cellules.

### Extensions possibles :
- Reconnaissance automatique des structures complexes (oscillateurs, vaisseaux).
- Support pour des grilles infinies.

Merci pour votre attention !
